### PR TITLE
Check Stream.CanRead before reading

### LINKED ISSUE #20: ArgumentException thrown from JsonWebResponseUtility.GetJsonAsAsync
A client application crashed with the following call stack:

```
ArgumentException: Stream was not readable. in System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen):82
System.IO.StreamReader..ctor(Stream stream):8
Faithlife.WebRequests.Json.JsonWebResponseUtility+<GetJsonAsAsync>d__3.MoveNext():146
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
Faithlife.WebRequests.Json.AutoWebServiceRequest`1+<ReadContentAsAsync>d__8.MoveNext():739
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
Faithlife.WebRequests.Json.AutoWebServiceRequest`1+<HandleResponseCoreAsync>d__6.MoveNext():299
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
Faithlife.WebRequests.WebServiceRequestBase`1+<HandleResponseAsync>d__9.MoveNext():147
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
Faithlife.WebRequests.WebServiceRequestBase`1+<GetResponseAsync>d__1.MoveNext():0
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
[client code]
```

The exception [is thrown here](https://github.com/dotnet/corefx/blob/c265373119bc0449d347862862b43de35a95b186/src/Common/src/CoreLib/System/IO/StreamReader.cs#L148-L151) if `!stream.CanRead`.

I think it's inappropriate to `catch ArgumentException` in client code; FaithlifeWebRequests should check the stream property and throw a `WebServiceException` if the stream can't be read.

### PR DESCRIPTION
**Pull request by bgrainger**
Fixes #20

### CODE REVIEW

File: src/Faithlife.WebRequests/Json/JsonWebResponseUtility.cs [hunk 1]
```diff
@@ -71,8 +71,11 @@ public static async Task<object> GetJsonAsAsync(this HttpResponseMessage respons
 		{
 			try
 			{
+				var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
+				if (!responseStream.CanRead)
+					throw HttpResponseMessageUtility.CreateWebServiceException(response, "Response Stream is not readable");
```
Comment (ejball) [inline src/Faithlife.WebRequests/Json/JsonWebResponseUtility.cs]: Nit: other exception messages are punctuated.

File: src/Faithlife.WebRequests/Json/JsonWebResponseUtility.cs [hunk 2]
```diff
@@ -71,8 +71,11 @@ public static async Task<object> GetJsonAsAsync(this HttpResponseMessage respons
 		{
 			try
 			{
+				var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
+				if (!responseStream.CanRead)
```
Comment (ejball) [inline src/Faithlife.WebRequests/Json/JsonWebResponseUtility.cs:77]: A comment explaining why this is necessary might be nice.

**Review by ejball — APPROVED** [review]
A comment exp
